Adding ability to specify branch or commit to use for the community n…
libremesh/lime-sdk pull request #55
Opened 2018-04-11 13:37 UTC by josmo

…etworks.

Helps to be able to specify a commit or branch to groups that are doing community managed builds

2018-04-13 01:28 UTC, nicopace commented
@josmo could you add information on how would you use it on the README file?

That way would be easy both to discuss about the functionality, and to test the implementation.

Thanks!

2018-04-13 03:44 UTC, josmo commented
@nicopace Let me know if that works? :)

2018-05-30 07:41 UTC, aparcar requested changes

2018-05-30 07:41 UTC, aparcar commented on cooker
> +            url="$(echo $communities_git | awk -F\; '{print $1}')"
does `${communities_git##*;}` works for you?

2018-05-30 07:41 UTC, aparcar commented on cooker
> +            branch="$(echo $communities_git | awk -F\; '{print $2}')"
`${communities_git%%;*}`

2018-05-30 07:41 UTC, aparcar commented on cooker
> +            url="$(echo $communities_git | awk -F\^ '{print $1}')"
same here and below

2018-05-30 07:41 UTC, aparcar commented on cooker
> +            git clone $communities_git $communities_dir || {
always add `"` around vars

2018-05-30 07:41 UTC, aparcar commented on options.conf
> +communities_git='https://github.com/libremesh/network-profiles.git'
I'd leave this as is and only add braces if needed - but just my opinion

2018-06-20 11:09 UTC, nicopace commented
Love the idea!
Thanks @aparcar for the review.
@josmo if you go through aparcar's corrections, it is good to go for me :)

2019-08-14 14:50 UTC, closed without merging